

//--CONSTANTS:--

//EMOTIONS ARRAY OF BOOLEANS
//EACH INDEX HAS A BOOL WHICH REPRESENTS TRUE FOR IF THEY SELECTED THAT EMOTION
//[HAPPY, SAD, FRUSTRATED, TIRED, STUDIOUS, ENERGETIC, ANXIOUS, NAUSEOUS]

export const HAPPY_INDEX = 0;
export const SAD_INDEX = 1;
export const FRUSTRATED_INDEX = 2;
export const TIRED_INDEX = 3;
export const STUDIOUS_INDEX = 4;
export const ENERGETIC_INDEX = 5;
export const ANXIOUS_INDEX = 6;
export const NAUSEOUS_INDEX = 7;

//ALLERGIES AND DIET RESTRICTIONS ARRAY OF BOOLEANS
//EACH INDEX HAS A BOOL WHICH REPRESENTS TRUE FOR IF THEY HAVE THE ALLERGY, AND TRUE IF THEY HAVE THE DIET RESTRICTION
//[PEANUTS, TREE_NUTS, DAIRY, GLUTEN, EGGS, SOYBEANS, SESAME, SHELLFISH, VEGAN, VEGETARIAN, PESCETARIAN, KETO, GLUTEN_FREE, KOSHER, HALAL]

//ALLERGENS:
export const PEANUT_INDEX = 0;
export const TREE_NUT_INDEX = 1;
export const DAIRY_INDEX = 2;
export const GLUTEN_INDEX = 3;
export const EGGS_INDEX = 4;
export const SOYBEANS_INDEX = 5;
export const SESAME_INDEX = 6;
export const SHELLFISH_INDEX = 7;
//DIETS:
export const VEGAN_INDEX = 8;
export const VEGETARIAN_INDEX = 9;
export const PESCETARIAN_INDEX = 10;
export const KETO_INDEX = 11;
export const GLUTEN_FREE_INDEX = 12;
export const KOSHER_INDEX = 13;
export const HALAL_INDEX = 14;

//--END OF CONSTANTS--

export const recipeData = [0, 1, 2, 3, 4, 5, 6, 7, 8];